### ISSUE TITLE
No field with type java.util.Collection exists in class PacketPlayOutSpawnEntityLiving

### ISSUE THREAD

**Issue by fax1ty** [iso2013/MultiLineAPI#44]
https://github.com/dmulloy2/ProtocolLib/issues/745

**Comment by frostalf** [comment]
Will take a look at it. Sorry been busy as of late.

**Comment by frostalf** [comment]
I believe this issue is resolved now. Let me know if it isn't and I will re-open the issue ticket.

**Comment by supertassu** [comment]
Hi @frostalf, this is still occuring on my server with MultiLineAPI `2.1.2-SNAPSHOT` downloaded from SpigotMC on Paper build 121 (MC 1.15.2).

**Comment by frostalf** [comment]
Ok, will take a look at it. Sorry for the late response. Thanks for informing it is still an issue.

**Comment by frostalf** [comment]
I will close this for now, the issue isn't because of multiline rather it is because of packetentityAPI which multiline depends on. Due to entities not requiring metadata in the packet anymore protocolib changed how metadata is obtained or used. So this will take some time in re-structuring packetentityAPI to resolve this. I created a new issue on PacketEntityAPI as that is where the underlying problem derives. 
https://github.com/iso2013/PacketEntityAPI/issues/15
